import React from 'react'
import Head from 'next/head'
import axios from 'axios'
import BlogLayout from '../../components/blog/layout'
import BlogDetail from '../../components/blog/detail'

const BlogPost = ({ detail, cnt }) => {
  return (
    <div>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>
      <BlogLayout cate={detail.cate} cnt={cnt}>
        <BlogDetail detail={detail} />
      </BlogLayout>
    </div>
  )
}

BlogPost.getInitialProps = async (context) => {
  console.log('???: ', context.query)
  const query = context.query.id
  const response = await axios.get(
    `http://localhost:3000/api/blog/${query}`
  )
  console.log('블로그 정보는 : ', response.data)
  return {
    detail: response.data,
    cnt: response.data.cnt
  }
}

export default BlogPost