import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import axios from 'axios'
import AppBar from '../../components/menu'
import styles from '/styles/Post.module.css'
import BlogLayout from '../../components/blog'
import ReactHtmlParser from 'react-html-parser'

const BlogDetail = ({ detail }) => {
  return (
    <div>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>
      <body>
        <AppBar>
          <BlogLayout cate={detail.cate}>
            <div style={{border: "2px solid red"}}>
              <section className={styles.title}>
                <h2>{detail.title}</h2>
                <div>{detail.date}</div>
              </section>
            </div>
          </BlogLayout>
          {/* <div className={styles.container}>
            <section className={styles.title}>
              <h2>{detail.title}</h2>
              <div>{detail.date}</div>
            </section>
            <section className={styles.content}>
              <div className={styles.contentImg}>
                <Image src='/images/backend.png' width={100} height={100} />
              </div>
              <div className={styles.contentDetail}>
                {detail.content}
              </div>
            </section>
            <section className={styles.comment}>
              <div className={st}>

              </div>
            </section>
          </div> */}
        </AppBar>
      </body>
    </div>
  )
}

BlogDetail.getInitialProps = async (context) => {
  console.log('???: ', context.query)
  const query = context.query.id
  const response = await axios.get(
    `http://localhost:3000/api/blog/${query}`
  )
  console.log('블로그 정보는 : ', response.data)
  return {
    detail: response.data
  }
}

export default BlogDetail