import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import axios from 'axios'
import AppBar from '../../components/menu'
import styles from '/styles/Post.module.css'
import BlogLayout from '../../components/blog/layout'
import BlogDetail from '../../components/blog/detail'
import ReactHtmlParser from 'react-html-parser'

const BlogPost = ({ detail, cnt }) => {
  return (
    <div>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>
      <AppBar>
        <BlogLayout cate={detail.cate} cnt={cnt}>
          <BlogDetail detail={detail} />
        </BlogLayout>
      </AppBar>
    </div>
  )
}

BlogPost.getInitialProps = async (context) => {
  console.log('???: ', context.query)
  const query = context.query.id
  const response = await axios.get(
    `http://localhost:3000/api/blog/${query}`
  )
  console.log('블로그 정보는 : ', response.data)
  return {
    detail: response.data,
    cnt: response.data.cnt
  }
}

export default BlogPost