import React, {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import axios from 'axios'
import AppBar from '../../components/menu'
import styles from '/styles/Blog.module.css'
import dynamic from 'next/dynamic'

const Editor = dynamic(() => import('../../components/editor'), {ssr: false})

const Create = ({ blogs, cate, cnt }) => {
  return (
    <div>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>

      <body>
        <AppBar>
          <Editor />
        </AppBar>
      </body>
    </div>
  )
}

Create.getInitialProps = async () => {
  const response = await axios.get('http://localhost:3000/api/blog')
  const data = response.data
  return {
    blogs : data.post,
    cate: data.cate,
    cnt: data.cnt,
  }
}

export default Create
