import React, {useState} from 'react'
import Head from 'next/head'
import axios from 'axios'
import dynamic from 'next/dynamic'

const Editor = dynamic(() => import('../../components/editor'), {ssr: false})

const Create = ({ cate }) => {
  return (
    <div>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>
      <Editor category={cate} />
    </div>
  )
}

Create.getInitialProps = async () => {
  const response = await axios.get('http://localhost:3000/api/blog/cate')
  const data = response.data
  return {
    cate: data,
  }
}

export default Create
