import React from 'react'
import axios from 'axios'
import styles from '/styles/Home.module.css'
import Image from 'next/image'
import Head from 'next/head'
import AppBar from '../components/menu'

const HomePage = ({ blogs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PKK Blog</title>
        <meta name="description" content="Generated by PKK" />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>
      <AppBar />
      <main className={styles.main}>
        <div className={styles.headerImg}>
          <Image src="/human.png" width={300} height={300} />
        </div>
        <div className={styles.msg}>
          <div>안녕하세요,</div>
          <div>메롱메롱메롱메롱</div>
        </div>
      </main>
      <div>
        <h1 className={styles.title}>
          Welcome to PKK Blog~
        </h1>
        <p className={styles.description}>
          This blog is made by
        </p>
        <div className={styles.grid}>
          <ul>
            {blogs.map((lst) => (
              <li key={lst.id}>
                <span>{lst.name}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://www.sunhomusic.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/sunhomusic_logo.png" alt="Vercel Logo" width={130} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

HomePage.getInitialProps = async () => {
  const response = await axios.get('http://localhost:3000/api/blog')
  const data = response.data
  console.log('data를 보자~ : ', data)
  return {
    blogs : data
  }
}

export default HomePage
